name: CI

on:
  push:
    branches:
      - "master"
      - "devops"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

env:
  TEMPLATENAME: client_${{ github.sha }}_${{ github.run_number }}

jobs:
  build:
    runs-on:
      ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print env
        run: env
      - name: Update package lists, install needed packages
        run: sudo apt update && sudo apt install libpqxx-dev libwxgtk3.0-gtk3-dev
      - name: Build application
        run: make
      - name: Prepare
        run: mv main.run ${{ env.TEMPLATENAME }}_${{ runner.os }}.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TEMPLATENAME }}.sh
          path: ${{ env.TEMPLATENAME }}_${{ runner.os }}.sh
          retention-days: 5
      # - name: Send notification in telegram
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_TO }}
      #     token: ${{ secrets.TELEGRAM_TOKEN }}
      #     message: |
      #       ${{ github.actor }} made an event ${{ github.event_name }}.
      #       Message:    ${{ github.event.commits[0].messages }}
      #       Repository: ${{ github.repository }}
      #       Changes:    https://github.com/${{ github.repository }}/commit/${{ github.sha }}
      #     document: client__${{ env.NAMEAPP }}.sh
