name: CI

on:
  push:
    branches:
      - "master"
      - "devops"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

env:
  CLIENT_NAME: client_${{ github.sha }}_${{ github.run_number }}_linux.sh

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check-success.outputs.status }}
    steps:
      - uses: actions/checkout@v3
      - name: Print env
        run: env
      - name: Update package lists, install needed packages
        run: sudo apt update && sudo apt install libpqxx-dev libwxgtk3.0-gtk3-dev
      - name: Build application
        run: make
      - name: Prepare artifacts' folder and file for condition of status
        if: always()
        run: |
          mkdir artifacts
          echo ${{ job.status }} > artifacts/status.txt
      - name: Print job status to outputs
        id: check-success
        if: always()
        run: |
          echo ::set-output name=status::$( echo ${{ job.status }} )
      - name: Prepare built client for uploading as artifact
        run:
          mv main.run artifacts/${{ env.CLIENT_NAME }}
      - name: List directory
        if: always()
        run: ls -laR
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.CLIENT_NAME }}
          path: artifacts

  send-notification:
    needs: build
    if: always()
    runs-on:
      ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.CLIENT_NAME }}
          path: artifacts
      - name: List directory
        run: ls -laR
      - name: Print build status
        run: echo ${{ needs.build.outputs.status }}
      - name: Send notification in telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} made an event -- ${{ github.event_name }}.
            Changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            Status: ${{ needs.build.outputs.status }}
          document: artifacts/${{ env.CLIENT_NAME }}
